DOPPLER_TOKEN_NAME = "SPROUT_SCOUT_DOPPLER_PROD_TOKEN"
DOPPLER_PROJECT_NAME = "pbapi"

REQUIRED_ENV_VAR_NAMES = [
    "POSTGRES_HOST",
    "POSTGRES_DB",
    "POSTGRES_USER",
    "POSTGRES_PASSWORD",
]
